# 1 "data/maps/DELTARUNE/scripts.pory"

# 2 "data/maps/DELTARUNE/scripts.pory"
DELTARUNE_MapScripts::
# 3 "data/maps/DELTARUNE/scripts.pory"
	.byte 0
# 4 "data/maps/DELTARUNE/scripts.pory"

# 5 "data/maps/DELTARUNE/scripts.pory"
DELTARUNE_EventScript_YouSavedBirch::
# 6 "data/maps/DELTARUNE/scripts.pory"
	msgbox DELTARUNE_Text_GET, MSGBOX_DEFAULT
# 7 "data/maps/DELTARUNE/scripts.pory"
	release
# 8 "data/maps/DELTARUNE/scripts.pory"
	end
# 9 "data/maps/DELTARUNE/scripts.pory"

# 10 "data/maps/DELTARUNE/scripts.pory"
DELTARUNE_Text_GET::
# 11 "data/maps/DELTARUNE/scripts.pory"
	.string "There's this myth about the\n"
# 12 "data/maps/DELTARUNE/scripts.pory"
	.string "ONE PIECE.\l"
# 13 "data/maps/DELTARUNE/scripts.pory"
	.string "It's apprently in this\l"
# 14 "data/maps/DELTARUNE/scripts.pory"
	.string "Town, But idk where.\l"
# 15 "data/maps/DELTARUNE/scripts.pory"
	.string "If you want, you can\l"
# 16 "data/maps/DELTARUNE/scripts.pory"
	.string "hunt for it!$"
